### ISSUE TITLE
Can it boot anything?

### ISSUE THREAD

**Issue by itscz-org** [AntAgna/XOSL#3]
Just tried your version because i have trouble with FreeDOS/Win7 Dual Boot using the original 1.15 and 1.16-OW versions. It can boot FreeDOS, but not Win7. Your version can't boot both.

**Comment by AntAgna** [comment]
Hi Chris. I created this repo to act as a source archive for XOSL to make sure the source code would not be lost in case the website and the Yahoo Group disappeared. This repo contains the original 1.1.5 version by Geurt Vos in 2000 and the versions 1.1.7 and 1.1.8 that contain a few improvements by awl. XOSL was built when a high end computer had a 750MHz Pentium 3 and ran Windows 98SE. Very little development has happened since. XOSL is compatible with most BIOS-based computers and most x86 OS from 2005 and before like Windows XP and Fedora 4. XOSL may not work well with UEFI-based computers and may have compatibility issues with modern OSes. The improvements in version 1.1.8 should help with compatibility with Windows Vista & 7 but I would not be surprised if it does not work. I can help you troubleshoot issues with XOSL if you are working with pre-2005 OSes on a BIOS-based x86 computer but I am afraid XOSL may not be the right tool if you want to use a recent computer or a recent version of Windows.

**Comment by itscz-org** [comment]
I tried it on a BIOS-based socket 939 machine with IDE devices...
